version: '3'
services:
  json-server:
    image: clue/json-server
    command:
      - 'http://jsonplaceholder.typicode.com/db'
    ports:
      - '80:80'
    # logging:
    #   driver: awslogs
    #   options:
    #     awslogs-group: amathon-session
    #     awslogs-region: ap-northeast-2
    #     awslogs-stream-prefix: amathon