version: '3'
services:
  json-server:
    image: clue/json-server
    command:
      - 'http://jsonplaceholder.typicode.com/db'
    ports:
      - '80:80'
  apollo-server:
    build:
      context: .
      dockerfile: ./apollo-server/Dockerfile
    ports:
      - '4000:4000'
    links:
      - json-server
    command: 'node src/index.js'
    working_dir: '/usr/src/apollo-server'